save_path: logs

long_term_memory: false
host: "localhost:9200"
max_turns: 999
window_size: 1536
memory_size: 512
temp_path: /tmp
defaults:
  - discord: infolumi
  - template: base
  - model: chatgpt
  - _self_
